### ISSUE TITLE
Exception in wasmJS

### ISSUE THREAD

**Issue by tprochazka** [Lavmee/constraintlayout-compose-multiplatform#94]
It works well on Android Target, but when I run it on wasmJS, it crashes already with this code

```
    ConstraintLayout() {
    }
```

like this
```
ERROR
[object WebAssembly.Exception]
    at handleError (webpack-internal:///../../node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///../../node_modules/webpack-dev-server/client/overlay.js:271:7)
```

I'm using Compose 1.7.1

I tried also downgrading to 1.7.0 and it then failed on 

```
WebAssembly.instantiate(): Import #4277 "./skiko.mjs" "org_jetbrains_skia_Canvas__1nSaveLayerSaveLayerRecRect": function import requires a callable
LinkError: WebAssembly.instantiate(): Import #4277 "./skiko.mjs" "org_jetbrains_skia_Canvas__1nSaveLayerSaveLayerRecRect": function import requires a callable
```

**Comment by tprochazka** [comment]
But I tried demo directly in this repository and it works, but for some reason it is really slow.
Slow response to click.

**Comment by tprochazka** [comment]
I found what causing it, some libraries, for example

`implementation("org.jetbrains.androidx.navigation:navigation-compose:2.8.0-alpha10")`
or 
`implementation("org.jetbrains.compose.ui:ui-graphics:1.7.0")`

If I add any of these two, just one is enought, even demo in this repo will crash in wasmJS

**Comment by tprochazka** [comment]
At the end. 
It is possible to solve it, just by custom build with the same version of compose as I'm using.

**Comment by Lavmee** [comment]
Could you try version 0.5.1?

**Comment by tprochazka** [comment]
Just tested and it works well. Thanks!
